/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IFeeCollector } from "../IFeeCollector";

export class IFeeCollector__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IFeeCollector {
    return new Contract(address, _abi, signerOrProvider) as IFeeCollector;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_payer",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_amount",
        type: "uint256",
      },
    ],
    name: "depositFee",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];
