/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IFeeCollectorCallback } from "../IFeeCollectorCallback";

export class IFeeCollectorCallback__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IFeeCollectorCallback {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IFeeCollectorCallback;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_amount",
        type: "uint256",
      },
    ],
    name: "feeCallback",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];
