/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import { Contract, ContractFactory, Overrides } from "@ethersproject/contracts";

import type { TestHelper } from "../TestHelper";

export class TestHelper__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(overrides?: Overrides): Promise<TestHelper> {
    return super.deploy(overrides || {}) as Promise<TestHelper>;
  }
  getDeployTransaction(overrides?: Overrides): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): TestHelper {
    return super.attach(address) as TestHelper;
  }
  connect(signer: Signer): TestHelper__factory {
    return super.connect(signer) as TestHelper__factory;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): TestHelper {
    return new Contract(address, _abi, signerOrProvider) as TestHelper;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "uint16",
        name: "tick",
        type: "uint16",
      },
      {
        internalType: "uint64",
        name: "idx",
        type: "uint64",
      },
    ],
    name: "getOrderId",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b5060fd8061001f6000396000f3fe6080604052348015600f57600080fd5b506004361060285760003560e01c80633c6b01f914602d575b600080fd5b603c60383660046081565b604e565b60405190815260200160405180910390f35b600060588383605f565b9392505050565b6000605867ffffffffffffffff83166001600160f01b031960f086901b1660cb565b60008060408385031215609357600080fd5b823561ffff8116811460a457600080fd5b9150602083013567ffffffffffffffff8116811460c057600080fd5b809150509250929050565b6000821982111560eb57634e487b7160e01b600052601160045260246000fd5b50019056fea164736f6c634300080c000a";
